---
title: "Obtenção dos dados"
---

O tomate (*Solanum lycopersicum*) é uma cultura amplamente cultivada, reconhecida por seu valor econômico e nutricional. No entanto, esta cultura é frequentemente acometida por doenças foliares, como as manchas causadas por *Alternaria solani*, que comprometem sua produtividade. O objetivo deste experimento foi analisar os efeitos de diferentes tratamentos, incluindo agentes de biocontrole, na severidade das manchas foliares e na produtividade do tomate.

Os tratamentos avaliados incluíram:

1.  Controle (Check)

2.  Agente de biocontrole A (Bio agent A)

3.  Agente de biocontrole B (Bio agent B)

4.  Fungicida (Fungicide)

O experimento foi conduzido com 10 repetições, e as observações foram feitas em múltiplos intervalos de tempo: 0, 4, 8, 12, 16, 20, 24 e 28 dias.

Além disso, três isolados de *Alternaria solani* foram utilizados no experimento:

1.  As1

2.  As2

3.  As3

A análise dos dados buscou compreender como a severidade da doença influenciava o rendimento do tomate, proporcionando insights valiosos para o manejo efetivo das doenças foliares nesta cultura e a eficácia dos agentes de biocontrole aplicados.

Detentor dos dados analisados: **Ricardo Gomes Tomáz** ([contato](ricardogomesagro@gmail.com))

# Hipóteses

### Hipóteses para a Interação entre Isolado e Severidade das Manchas Foliares:

-   Hipótese Nula (H0): Não há interação significativa entre os diferentes isolados (As1, As2, As3) e os tratamentos na severidade das manchas foliares ao longo do tempo. A severidade das manchas foliares é influenciada independentemente pelos isolados e tratamentos.

-   Hipótese Alternativa (H1): Há uma interação significativa entre os diferentes isolados (As1, As2, As3) e os tratamentos na severidade das manchas foliares ao longo do tempo. A severidade das manchas foliares é influenciada de maneira diferente dependendo da combinação dos isolados e tratamentos.

### Hipóteses para a Severidade das Manchas Foliares:

-   Hipótese Nula (H0): Não há diferença significativa na severidade das manchas foliares entre os tratamentos ao longo do tempo.

-   Hipótese Alternativa (H1): Existe uma diferença significativa na severidade das manchas foliares entre pelo menos dois dos tratamentos ao longo do tempo.

### Hipóteses para a Regressão Linear entre Severidade e Tempo:

-   Hipótese Nula (H0): Não há relação significativa entre o tempo (dias) e a severidade das manchas foliares (coeficiente angular = 0).

-   Hipótese Alternativa (H1): Há uma relação significativa entre o tempo (dias) e a severidade das manchas foliares (coeficiente angular ≠ 0).\

### Hipóteses para o rendimento do Tomate:

-   Hipótese Nula (H0): Não há diferença significativa no rendimento do tomate entre os tratamentos.

-   Hipótese Alternativa (H1): Existe uma diferença significativa no rendimento do tomate entre pelo menos dois dos tratamentos.\

### Hipóteses para a Análise de Correlação:

-   Hipótese Nula (H0): Não há correlação significativa entre a severidade das manchas foliares no dia 28 e o rendimento do tomate no dia 28 (coeficiente de correlação de Pearson = 0).

-   Hipótese Alternativa (H1): Há uma correlação significativa entre a severidade das manchas foliares no dia 28 e o rendimento do tomate no dia 28. (coeficiente de correlação de Pearson ≠ 0).
